/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlysinhvien;

import java.awt.Color;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Thinh Le
 */
public class UI_DangNhap extends javax.swing.JFrame {

    private Socket socket;
    private ObjectOutputStream outputStream;

    /**
     * Creates new form UI_DangNhap
     */
    public UI_DangNhap() {
        initComponents();
        connectToServer();
    }

    private void connectToServer() {
        try {
            socket = new Socket("localhost", 12345);
            outputStream = new ObjectOutputStream(socket.getOutputStream());
            System.out.println("Connected to server");
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Cannot connect to the server.", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1_UI_DangNhap_Usrname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField1_UI_DangNhap_Pwd = new javax.swing.JPasswordField();
        jButton1_UI_DangNhap_Login = new javax.swing.JButton();
        jButton2_UI_DangNhap_SinhVien = new javax.swing.JButton();
        jCheckBox1_UI_DangNhap_show = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel4.setText("jLabel4");

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        jLabel1.setText("Log in");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel2.setText("Quản Lý Sinh Viên");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Username");

        jTextField1_UI_DangNhap_Usrname.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jTextField1_UI_DangNhap_Usrname.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1_UI_DangNhap_Usrname.setText("Username");
        jTextField1_UI_DangNhap_Usrname.setMargin(new java.awt.Insets(1, 8, 1, 8));
        jTextField1_UI_DangNhap_Usrname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1_UI_DangNhap_UsrnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1_UI_DangNhap_UsrnameFocusLost(evt);
            }
        });
        jTextField1_UI_DangNhap_Usrname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_UI_DangNhap_UsrnameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Password");

        jPasswordField1_UI_DangNhap_Pwd.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jPasswordField1_UI_DangNhap_Pwd.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField1_UI_DangNhap_Pwd.setText("password");
        jPasswordField1_UI_DangNhap_Pwd.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jPasswordField1_UI_DangNhap_Pwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1_UI_DangNhap_PwdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1_UI_DangNhap_PwdFocusLost(evt);
            }
        });

        jButton1_UI_DangNhap_Login.setText("Log in");
        jButton1_UI_DangNhap_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_UI_DangNhap_LoginActionPerformed(evt);
            }
        });

        jButton2_UI_DangNhap_SinhVien.setText("Sinh Viên xem điểm");
        jButton2_UI_DangNhap_SinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_UI_DangNhap_SinhVienActionPerformed(evt);
            }
        });

        jCheckBox1_UI_DangNhap_show.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jCheckBox1_UI_DangNhap_show.setText("Show Password");
        jCheckBox1_UI_DangNhap_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1_UI_DangNhap_showActionPerformed(evt);
            }
        });

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jCheckBox1_UI_DangNhap_show)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1_UI_DangNhap_Usrname)
                    .addComponent(jPasswordField1_UI_DangNhap_Pwd, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1_UI_DangNhap_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2_UI_DangNhap_SinhVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(jTextField1_UI_DangNhap_Usrname, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addComponent(jPasswordField1_UI_DangNhap_Pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1_UI_DangNhap_show)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_UI_DangNhap_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2_UI_DangNhap_SinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1_UI_DangNhap_UsrnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_UI_DangNhap_UsrnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_UI_DangNhap_UsrnameActionPerformed

    private void jTextField1_UI_DangNhap_UsrnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_UI_DangNhap_UsrnameFocusGained
        if (jTextField1_UI_DangNhap_Usrname.getText().equals("Username")) {
            jTextField1_UI_DangNhap_Usrname.setText("");
            jTextField1_UI_DangNhap_Usrname.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_jTextField1_UI_DangNhap_UsrnameFocusGained

    private void jTextField1_UI_DangNhap_UsrnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_UI_DangNhap_UsrnameFocusLost
        if (jTextField1_UI_DangNhap_Usrname.getText().equals("")) {
            jTextField1_UI_DangNhap_Usrname.setText("Username");
            jTextField1_UI_DangNhap_Usrname.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField1_UI_DangNhap_UsrnameFocusLost


    private void jPasswordField1_UI_DangNhap_PwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1_UI_DangNhap_PwdFocusGained
        jCheckBox1_UI_DangNhap_show.setSelected(false);
        jPasswordField1_UI_DangNhap_Pwd.setEchoChar('•');
        String pwd = String.valueOf(jPasswordField1_UI_DangNhap_Pwd.getPassword());
        if (pwd.toLowerCase().equals("password")) {
            jPasswordField1_UI_DangNhap_Pwd.setText("");
            jPasswordField1_UI_DangNhap_Pwd.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPasswordField1_UI_DangNhap_PwdFocusGained

    private void jPasswordField1_UI_DangNhap_PwdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1_UI_DangNhap_PwdFocusLost
        String password = String.valueOf(jPasswordField1_UI_DangNhap_Pwd.getPassword());
        if (password.toLowerCase().equals("password") || password.toLowerCase().equals("")) {
            jPasswordField1_UI_DangNhap_Pwd.setText("Password");
            jPasswordField1_UI_DangNhap_Pwd.setEchoChar((char) 0);
            jPasswordField1_UI_DangNhap_Pwd.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jPasswordField1_UI_DangNhap_PwdFocusLost

    private void jCheckBox1_UI_DangNhap_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1_UI_DangNhap_showActionPerformed
        jCheckBox1_UI_DangNhap_show.setSelected(true);
        if (jCheckBox1_UI_DangNhap_show.isSelected()) {
            jPasswordField1_UI_DangNhap_Pwd.setEchoChar((char) 0);
        } else {
            jPasswordField1_UI_DangNhap_Pwd.setEchoChar('•');
        }
    }//GEN-LAST:event_jCheckBox1_UI_DangNhap_showActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int a = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0)//0=yes,1=no:
        {
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1_UI_DangNhap_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_UI_DangNhap_LoginActionPerformed
        String username = jTextField1_UI_DangNhap_Usrname.getText();
        String password = new String(jPasswordField1_UI_DangNhap_Pwd.getPassword());

        try {
            outputStream.writeObject(username);
            outputStream.writeObject(password);

            ObjectInputStream inputStream = new ObjectInputStream(socket.getInputStream());
            boolean isAuthenticated = (boolean) inputStream.readObject();

            if (isAuthenticated) {
                JOptionPane.showMessageDialog(this, "Login successful!");
                new giaoDienGV().setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Tài khoản hoặc mật khẩu không hợp lệ.", "Error!", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException | ClassNotFoundException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi kết nối.", "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1_UI_DangNhap_LoginActionPerformed

    private void jButton2_UI_DangNhap_SinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_UI_DangNhap_SinhVienActionPerformed
          java.awt.EventQueue.invokeLater(() -> {
                new quanlysinhvien.JFStudent().setVisible(true);
                this.dispose();
            });
    }//GEN-LAST:event_jButton2_UI_DangNhap_SinhVienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                new UI_DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_UI_DangNhap_Login;
    private javax.swing.JButton jButton2_UI_DangNhap_SinhVien;
    private javax.swing.JCheckBox jCheckBox1_UI_DangNhap_show;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1_UI_DangNhap_Pwd;
    private javax.swing.JTextField jTextField1_UI_DangNhap_Usrname;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
